#!/usr/bin/env python3
"""Lift the oracle's run definitions into a TSV the C++ engine can read.

The engine does not tokenize. The oracle already pins the exact input_ids for
every run, and re-deriving them in C++ would mean a second tokenizer whose
disagreements would surface as engine bugs. So the ids travel as data.

    python scripts/export_runs.py          # oracle/manifest.json -> engine/runs.tsv

Format, one line per run:

    name <TAB> escaped_prompt <TAB> id,id,id,...

The prompt is carried only so the engine's own manifest can echo it; nothing in
the engine computes on it. Escapes are \\\\, \\n, \\r, \\t -- enough for the
`newline` run, which is a bare "\\n" and would otherwise end the line.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "oracle" / "manifest.json"
DEFAULT_OUT = ROOT / "engine" / "runs.tsv"


def escape(s: str) -> str:
    return (s.replace("\\", "\\\\")
             .replace("\n", "\\n")
             .replace("\r", "\\r")
             .replace("\t", "\\t"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text())

    lines = [
        f"# generated by scripts/export_runs.py from {args.manifest.name}",
        "# name\tprompt (escaped)\tinput_ids",
    ]
    for run in manifest["runs"]:
        ids = ",".join(str(i) for i in run["input_ids"])
        lines.append(f"{run['name']}\t{escape(run['prompt'])}\t{ids}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")

    print(f"wrote {args.out}  ({len(manifest['runs'])} runs)")
    for run in manifest["runs"]:
        print(f"  {run['name']:10s} T={run['n_tokens']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
