#!/usr/bin/env python3
"""Tokenize the benchmark prompt into a TSV the C++ bench tool can read.

Same reasoning as scripts/export_runs.py: the engine does not tokenize, so the
ids travel as data. Same format, so engine/src/runs.cpp reads both.

    python scripts/export_bench_prompt.py        # -> bench/prompts.tsv

The oracle's prompts are not reusable here. The longest of them is 90 tokens,
and the benchmark wants a prompt long enough that prefill is dominated by the
matmuls rather than by fixed overhead. So the text below is the benchmark's
own, and it is truncated to exactly --tokens ids -- an exact length matters
because prefill cost is the thing being measured and it scales with T.

The text is only a carrier for a realistic token distribution; nothing in the
benchmark computes on it. It is committed as ids in bench/prompts.tsv, so a
benchmark result stays reproducible even if this script or the tokenizer moves.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_WEIGHTS = ROOT / "weights" / "gpt2-124m"
DEFAULT_OUT = ROOT / "bench" / "prompts.tsv"

# Continues the register of the oracle's `long` prompt: ordinary English prose,
# no code, no degenerate whitespace. Comfortably longer than 128 tokens so the
# truncation below has something to cut.
TEXT = (
    "The history of computing is often told as a story of hardware, but the "
    "more interesting story is arguably the one about abstraction. Every "
    "generation of programmers has built a layer that let the next generation "
    "forget something the previous one had to know by heart. The machine "
    "underneath has grown steadily less visible as a result, and the cost of "
    "that invisibility is paid in the moments when the abstraction leaks and "
    "somebody has to reason about cache lines, denormals, or the order in "
    "which a sum was accumulated. Performance work is largely the practice of "
    "deciding which of those forgotten details deserve to be remembered "
    "again, and in what order, and how to prove that remembering them did not "
    "quietly change the answer that the program was computing in the first "
    "place."
)

NAME = "bench128"


def escape(s: str) -> str:
    return (s.replace("\\", "\\\\")
             .replace("\n", "\\n")
             .replace("\r", "\\r")
             .replace("\t", "\\t"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--weights", type=Path, default=DEFAULT_WEIGHTS,
                        help="directory holding the tokenizer files")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--tokens", type=int, default=128,
                        help="truncate the prompt to exactly this many ids")
    parser.add_argument("--name", default=NAME)
    args = parser.parse_args()

    from transformers import AutoTokenizer  # tokenization only
    tok = AutoTokenizer.from_pretrained(str(args.weights))

    ids = tok(TEXT).input_ids
    if len(ids) < args.tokens:
        raise SystemExit(
            f"TEXT tokenizes to {len(ids)} ids, fewer than the requested "
            f"{args.tokens}; lengthen TEXT")
    ids = ids[:args.tokens]

    # Round-trip so the prompt recorded alongside the ids is the text those ids
    # actually decode to, not the untruncated source.
    prompt = tok.decode(ids)

    lines = [
        "# generated by scripts/export_bench_prompt.py",
        "# name\tprompt (escaped)\tinput_ids",
        f"{args.name}\t{escape(prompt)}\t{','.join(str(i) for i in ids)}",
    ]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")

    print(f"wrote {args.out}  ({args.name}, T={len(ids)})")
    print(json.dumps(prompt)[:100] + " ...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
